//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNotepad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapNotepad.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already registered.
        /// </summary>
        public static string AlertEmailAlredyRegistred {
            get {
                return ResourceManager.GetString("AlertEmailAlredyRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is incorrect.
        /// </summary>
        public static string AlertEmailRequared {
            get {
                return ResourceManager.GetString("AlertEmailRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect E-mail.
        /// </summary>
        public static string AlertIncorrectEmail {
            get {
                return ResourceManager.GetString("AlertIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name.
        /// </summary>
        public static string AlertIncorrectName {
            get {
                return ResourceManager.GetString("AlertIncorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string AlertIncorrectPassword {
            get {
                return ResourceManager.GetString("AlertIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string AlertInvalidLoginOrPassword {
            get {
                return ResourceManager.GetString("AlertInvalidLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not start with a number,  name length must be no less than 1 characters and no more than 16 characters.
        /// </summary>
        public static string AlertNameRequared {
            get {
                return ResourceManager.GetString("AlertNameRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not confirmed.
        /// </summary>
        public static string AlertNotConfirmPassword {
            get {
                return ResourceManager.GetString("AlertNotConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain from 8 to 16 characters, among which there must be a capital letter, a small letter, and also a number.
        /// </summary>
        public static string AlertPasswordRequared {
            get {
                return ResourceManager.GetString("AlertPasswordRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string PageBattonDelete {
            get {
                return ResourceManager.GetString("PageBattonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string PageBattonEdit {
            get {
                return ResourceManager.GetString("PageBattonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIHNUP.
        /// </summary>
        public static string PageButtonHyperLink {
            get {
                return ResourceManager.GetString("PageButtonHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string PageButtonSignIn {
            get {
                return ResourceManager.GetString("PageButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string PageButtonSignUp {
            get {
                return ResourceManager.GetString("PageButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorite.
        /// </summary>
        public static string PageLableForRadiobatton {
            get {
                return ResourceManager.GetString("PageLableForRadiobatton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        public static string PageMapTitle {
            get {
                return ResourceManager.GetString("PageMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lable.
        /// </summary>
        public static string PagePinLable {
            get {
                return ResourceManager.GetString("PagePinLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string PagePinLatitude {
            get {
                return ResourceManager.GetString("PagePinLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string PagePinLongitude {
            get {
                return ResourceManager.GetString("PagePinLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN LIST.
        /// </summary>
        public static string PagePinTitle {
            get {
                return ResourceManager.GetString("PagePinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string PagePlaceholderEmail {
            get {
                return ResourceManager.GetString("PagePlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PagePlaceholderName {
            get {
                return ResourceManager.GetString("PagePlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string PagePlaceholderPasswConfirm {
            get {
                return ResourceManager.GetString("PagePlaceholderPasswConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PagePlaceholderPassword {
            get {
                return ResourceManager.GetString("PagePlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search pin....
        /// </summary>
        public static string PagePlaceholderSearchBar {
            get {
                return ResourceManager.GetString("PagePlaceholderSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string PageSignInTitle {
            get {
                return ResourceManager.GetString("PageSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string PageSignUpTitle {
            get {
                return ResourceManager.GetString("PageSignUpTitle", resourceCulture);
            }
        }
    }
}
